# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
