# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='domaine',
            field=models.CharField(choices=[('technology', 'technology'), ('mecanique', 'mecanique')], default=1, max_length=100),
        ),
    ]
