# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_search', '0005_auto_20170402_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='region',
            field=models.CharField(choices=[('sfax', 'sfax'), ('monastir', 'monastir'), ('gafsa', 'gafsa'), ('tunis', 'tunis'), ('sousse', 'sousse'), ('gabes', 'gabes'), ('mahdia', 'mahdia'), ('beja', 'beja'), ('tataouine', 'tataouine')], default=1, max_length=100),
        ),
    ]
