# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_search', '0007_auto_20171021_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
