# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs_search', '0008_auto_20171021_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_search.Profile'),
        ),
    ]
