# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_search', '0009_auto_20190204_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_cv_file', models.FileField(upload_to='')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_search.Annonce')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_search.Profile')),
            ],
        ),
    ]
