# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_search', '0011_auto_20190221_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
